### ISSUE TITLE
Carriage return

### ISSUE THREAD

**Issue by rfael** [diondokter/at-commands#1]
Hey, 
AT commands should end witch `\r\n` instead of only `\n`.
I think a configurable postfix would be good idea.

**Comment by diondokter** [comment]
Oh hey!
Someone is actually using this!

Oof... I should finish parsing at some point...

Yeah, it'd be a good idea indeed. Let me see what I can do.

**Comment by diondokter** [comment]
So I released an update!
Changed the default to `\r\n` and added a new function to allow you to specify it yourself: https://github.com/diondokter/at-commands/blob/77adeb8a6e38c3192137a832845e03555b15b5a8/src/builder.rs#L233

Hopefully this helps you :)
If there's anything else, just open an issue and I'll see what I can do!
